project:
  type: website


website:
  title: ""
  site-url: "https://faculty.washington.edu/masiello/"
  repo-url: "https://github.com/MasielloGroup/MasielloGroupWebsite"
  favicon: images/favicon.png
  google-analytics: "UA-177339812-1"
  page-navigation: false
  search: true
  page-footer: 
    background: "#f0eeeb"
    center: © 2023  &middot; Made with {{< fa brands r-project >}} and 
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)
  
  navbar:
    search: true
    logo: images/logo.png
    background: "#f0eeeb"
    logo-alt: "Masiello Research Group"
    left:
      - href: news/index.qmd
      - href: people/index.qmd
      - href: research/index.qmd
      - href: publications/index.qmd
      - text: NSF DMREF
        href: dmref
      - href: codes/index.qmd
        text: Codes
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: 
      - styles/custom.scss
      - yeti
    toc: true
    link-external-newwindow: true



