project:
  type: website


website:
  title: ""
  site-url: "https://faculty.washington.edu/masiello/"
  repo-url: "https://github.com/MasielloGroup/MasielloGroupWebsite"
  favicon: images/favicon.drawio.png
  google-analytics: "UA-177339812-1"
  #back-to-top-navigation: true
  page-navigation: false
  search: true
  page-footer: 
    background: "#F6F5F3"
    center: © 2023  &middot; Made with {{< fa brands r-project >}} and 
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/) 
    right:
      - icon: github
        href: https://github.com/MasielloGroup/MasielloGroupWebsite
  
  navbar:
    search: true
    logo: images/logo.drawio.png
    background: "#F6F5F3"
    logo-alt: "Masiello Research Group"
    left:
      - href: people/index.qmd
        text: people
      - href: research/index.qmd
      - href: publications/index.qmd
      # - text: NSF DMREF
      #   href: dmref
      - href: codes/index.qmd
        text: Codes
      - href: news/index.qmd
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: 
      - styles/custom.scss
      - yeti
    mainfont: Nunito Sans
    toc: true
    link-external-newwindow: true
    date-format: "MMM YYYY"
    smooth-scroll: true
    resources:
      - images



