project:
  type: website
preview:
    port: 4200
    browser: true

website:
  title: "The Bruna Lab"
  site-url: "https://brunalab.org/"
  repo-url: "https://github.com/BrunaLab/QuartoBrunaWebsite"
  favicon: images/bruna-logo-bird.png
  # google-analytics: "UA-177339812-1"
  twitter-card: true
  back-to-top-navigation: true
  page-navigation: false
  search: true
  # body-footer: 'TEST'
  page-footer: 
    background: "#FFFFFF"
    left: '[![](/images/bruna-logo-full.png){fig-alt="brunalab logo" height=110px}](https://tropicos.netlify.app/)'
    center: '[![](/images/Vertical_Logo_Reversed-RGB_Raster-BLUE2.png){fig-alt="UF logo" height=110px}](https://www.ufl.edu/)'
    # center: Made by Emilio M. Bruna with <br> {{< fa brands r-project fa-2xs >}} and 
    #   [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=105px}](https://quarto.org/) 
    right: Made with {{< fa brands r-project size=2x >}} and 
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" height=30px}](https://quarto.org/) <br>
      Code at {{< fa brands github  size=2x >}}<br>
    
    
      # - icon: github color: fill='#465672' {fig-alt="Quarto" width=105px}
      #   href: https://github.com/BrunaLab/QuartoBrunaWebsite
      # 
    
  navbar:
    search: true
    title: false
    # logo: images/bruna-logo-bird.png
    logo: images/bruna-logo-full.png
    background: "#FFFFFF"
    logo-alt: "Bruna Lab"
    left:
      - href: people/embruna/index.qmd
        text: Emilio M. Bruna
      - href: people/index.qmd
        text: lab members
      - href: projects/index.qmd
      - href: publications/index.qmd
        text: publications
      - href: courses/index.qmd
        text: courses
      - href: contact.qmd
        text: Contact

  # sidebar:
#  link each group of sidebar entries with a navbar entry by matching their titles and listing the page linked from the navbar as the first content in the sidebar
    # - id: dmref
    #    title: "NSF DMREF"
      # logo: "images/dmref-logo.png"
      # logo-href: dmref/index.qmd #avail quarto v 1.5
      # contents: 
      #   - href: dmref/index.qmd
      #     text: Welcome to DMREF
      #   - href: dmref/people/index.qmd
      #     text: The DMREF Team
      #   - href: dmref/publications/index.qmd
      #     text: DMREF-Related Publications
      #   - href: dmref/codes/index.qmd
      #     text: Computer Codes
      #   - href: dmref/data/index.qmd
      #     text: Team Data

    # - id: empty-to-suppress-sidebars-on-other-pages


format:
  html:
    theme: 
      - styles/custom.scss
      - lux
    fontcolor: black
    fontsize: x-large
    mainfont: Nunito Sans
    toc: true
    link-external-newwindow: true
    date-format: "MMM YYYY"
    smooth-scroll: true
    resources:
      - images
# filters:
#   - auto-dark


